version: '3.3'

services:
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:5.0-focal
    container_name: dotnet-container
    volumes:
      - /workspace/fs-advent-2020:/workspace/fs-advent-2020
    working_dir: /workspace/fs-advent-2020
    command: >
      bash -c "dotnet tool restore && dotnet fable watch ./src/App/App.fsproj --outDir ./src/Web/src/bin"

  node:
    image: node:15.8.0
    container_name: node-container
    volumes:
      - /workspace/fs-advent-2020/src/Web:/app
    ports:
      - "8080:8080"
    depends_on:
      - dotnet
    working_dir: /app
    command: >
      bash -c "yarn && yarn start"
